import { Layout } from '@/components'
import { ReactNode } from 'react'
import '../styles/globals.css'

export const metadata = {
  title: 'Phanox | Ecommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='pt-BR'>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
